### PR TITLE
Explore

### PR DESCRIPTION
**Pull request by MaddieandAngel**
- Implemented EnemyBehaviour and related classes
- Implemented use case where an enemy is generated and the game moves to the battle section
- Completed implementation of the title screen's interactor
- Started implementation of Main
- Updated TurnSelectView and ExploreView to include the player's stats

### CODE REVIEW

**Review by mikaylapradeepan — APPROVED** [review]
Looks good to me! Follows SOLID and has easy-to-read code.

**Review by SallyZhijing — APPROVED** [review]
-Don't see any problems with this code, looks like following CA and SOLID principle well, and the namings are very easy to understand.
-Maybe need to delete the comments like "copied from week5ca"(?)
-Maybe can create some test cases for the implementation

**Review by sarahlloydsmith — APPROVED** [review]
Notes:

- Need to add the card to the enemy's hand first before moving the temporary pile back to the deck, since a card will only be added to a pile if it is a card that has been drawn, so doing MovePileToDeck would not allow the card to be added to the enemy's hand
- When calculating card weakness cardSuit should be compared not cardValue. (Might not even need suit weaknesses depending on how we decide to calculate damage.
- DeckInterface needs to be used instead of Deck (but I know DeckInterface was only implemented after this)

Overall:
Good coding style, followed clean architecture and SOLID principles, good commit messages and pull request description. Tests need to be added.

**Review by sarahlloydsmith — APPROVED** [review]
Notes:

- Assuming for InBattleDataAccessObject getDeck and setDeck, will be changed to DeckInterface once DeckInterface is a part of main. Same with EnemyBehaviour
- For EnemyBehaviour, I agree with commenting out that line, since it doesn't seem necessary with your new implementation

Everything else looks good!

**Pull request merged**
